// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lifexp/Dashboard.tsx": () => import("../components/mockups/lifexp/Dashboard.tsx"),
  "./components/mockups/lifexp/Onboarding.tsx": () => import("../components/mockups/lifexp/Onboarding.tsx"),
  "./components/mockups/lifexp/Profile.tsx": () => import("../components/mockups/lifexp/Profile.tsx"),
  "./components/mockups/lifexp/Quests.tsx": () => import("../components/mockups/lifexp/Quests.tsx"),
  "./components/mockups/lifexp/SignIn.tsx": () => import("../components/mockups/lifexp/SignIn.tsx")
};
